version: "2"
services:
        web:
          build: .
          ports:
                - "8000:5000"
          networks:
                - mynet
          links:
                - redis
        redis:
          image: redis:alpine
          ports:
              - "6379"
          networks:
               - mynet
networks:
        mynet:
